### ISSUE TITLE
На мобильном устройстве текст не масштабируется

### ISSUE THREAD

**Issue by nimargolis** [intrahouseio/intraHouse-Cherry#4]
Максим Вершинин

**Comment by fast0490f** [comment]
Связанная дискуссия #18

**Comment by fast0490f** [comment]
Привет @goodspeed1986,
Мы рады сообщить, что работа по данной задаче завершена. :rocket:
В скором времени мы выпустим новую версию, где можно будет проверить функционал.
Отследить новые версии и список изменений можно по [releases](https://github.com/intrahouseio/Doc/releases) или [milestones](https://github.com/intrahouseio/Doc/milestones). Не стесняйтесь возобновить задачу если у вас появятся вопросы.

**Comment by fast0490f** [comment]
firefox 55 new bug
