### ISSUE TITLE
Интеграция с mqtt

### ISSUE THREAD

**Issue by beho1der** [intrahouseio/intraHouse-Cherry#70]
Возможно ли добавить поддержку MQTT в виде плагина или например поддержку связку mosquitto через его возможность использовать  websocket? Это автоматически сделает возможность интеграции со всеми кто поддерживает данный протокол.

**Comment by fast0490f** [comment]
Добрый день,
в ближайшее время мы выпустим плагин для MQTT.

**Comment by beho1der** [comment]
Отличная новость,это позволит сильно расширить список интеграций,к сожалению процедуры написание плагинов не очень понятна.

**Comment by fast0490f** [comment]
@beho1der 
Добрый день, плагин доступен для скачивания https://intrahouse.ru/product/plugin-mqtt/
